path: /blog/author/adam-duvander
tag: author
title: Adam DuVander
subtitle: >-
  Adam DuVander is an API veteran, developer communicator, and principal
  consultant at EveryDeveloper. His work with developer-focused companies helps
  to better engage their audiences. You can find his technical content on Wired,
  Zapier, and SendGrid, among many others.
pageName: Contributing Editor
image: /images/duvander-headshot.jpg
color: black
tabs:
  - {}
actionBar:
  ctas:
    - color: purple
  enabled: false
meta:
  favicon: /images/mark_light_bg.png
  title: Adam DuVander | Stoplight
  robots: 'index, follow'
  twitter:
    title: Adam DuVander | Stoplight
    username: '@stoplightio'
pagination: {}
