path: /docs
title: Free Hosted Technical Docs
color: indigo
relatedTags:
  - blog-documentation
hero:
  title: Free Hosted Technical Docs
  particles: true
  subtitle: >-
    Generate beautiful technical documentation for your git projects
  image:
    alt: Documentation
    src: /images/docs_header.png
  ctas:
    - color: green
      href: /studio
      title: Author in Studio
      icon: ['fad', 'pencil-alt']
      rightIcon: ['fad', 'arrow-right']
    - title: Use Hubs for Company Docs
      href: /hubs
      color: orange
      icon: ['fad', 'book-open']
      rightIcon: ['fad', 'arrow-right']
actionBar:
  enabled: true
  text: 'Ready to Publish?'
  ctas:
    - color: accent
      href: 'https://stoplight.io/studio'
      title: Get started with Studio
    - color: grey-dark
      href: 'https://stoplight.io/p/login'
      title: Login with Github
      icon: ['fab', 'github']
featureSection:
    src: /images/docs/landing.png
  title: Built for Personal and Open Source projects
  description: >-
    Stoplight Docs are free and easy to use. Connect your Github and automatically generate technical documentation in seconds for any of your projects. One-click publish from [Stoplight Studio](/studio) or add the Stopight CLI to your CI/CD workflow.

  features:
    - description: >-
        Automatically generate documentation from your OpenAPI v2 and v3 documents. With a powerful request maker, your users will be able to try out your API directly from the docs. Our JSON Schema viewer allows them to easily navigate deeply nested request and response structures.
      image: /images/docs/request-maker.png
      shortName: OpenAPI v2/v3
      title: Generate from OpenAPI v2/v3

    - description: >-
        Stoplight Docs uses a powerful Markdown engine built on top of the CommonMark spec. Enhance your documentation with embedded models, code snippets, call outs and more to give your users the best experience.
      image: /images/docs/jsv.png
      shortName: Powerful Markdown
      title: Powerful Markdown Rendering

    - description: >-
        Write content using your favorite editor, such as [Stoplight Studio](/studio), then use git to push changes into a git repository on Github, Bitbucket, Gitlab, etc. Before publishing, you can check out a preview of the updated docs along with a breakdown of all the changes.
      image: /images/docs/preview-changelog.png
      shortName: Preview & Changelog
      title: Preview & Changelog

    - description: >-
        Connect your Github account to one-click publish from [Stoplight Studio](/studio) or use the Stoplight CLI to automate your documentation process by integrating it into your existing CI/CD workflow.
      image: /images/docs/git.png
      shortName: Git Integration
      title: Publish from anywhere
meta:
  description: >-
    Stoplight Docs are free and easy to use. Connect your Github and automatically generate technical documentation in seconds for any of your projects. One-click publish from [Stoplight Studio](/studio) or add the Stopight CLI to your CI/CD workflow.
  favicon: /images/mark_light_bg.png
  image: /images/docs/landing.png
  title: Free Hosted Technical Docs | Stoplight
  robots: 'noindex, follow'
  twitter:
    description: >-
      Stoplight Docs are free and easy to use. Connect your Github and automatically generate technical documentation in seconds for any of your projects. One-click publish from [Stoplight Studio](/studio) or add the Stopight CLI to your CI/CD workflow.
    image: /images/docs/landing.png
    title: Free Hosted Technical Docs | Stoplight
    username: '@stoplightio'
