path: /docs
title: Simple, Lightweight Documentation
color: indigo
relatedTags:
  - blog-documentation

hero:
  title: Simple, Lightweight Documentation
  subtitle: >-
    Generate beautiful technical documentation for any of your git projects
  bgColor: indigo
  image:
    alt: Documentation
    src: /images/docs/landing.png

featureSection:
  title: Built for Open Source
  description: >-
    Create API documentation in seconds using any git repository. Combine OpenAPI Specifications (formerly known as Swagger) with Markdown to create robust, searchable, [API documentation](/api-documentation-guide/basics/)
    for any project. One-click publish from [Stoplight Studio](/studio) or add the Stopight CLI in your CI/CD workflow.

  features:
    - description: >-
        TODO
      image: /images/docs_feature_3.png
      shortName: Git Integration
      title: Git Integration

    - description: >-
        Never have out-of-date documentation. Use the Stoplight CLI to
        automate your documentation process by integrating it into your existing
        CI/CD workflow.
      image: /images/docs_feature_3.png
      shortName: Publish from CI/CD
      title: Automated API Documentation

    - description: >-
        Never have out-of-date documentation. Use the Stoplight CLI to
        automate your documentation process by integrating it into your existing
        CI/CD workflow.
      image: /images/docs_feature_3.png
      shortName: Stoplight Studio Integration
      title: Stoplight Studio Integration

  actionBar:
    enabled: true
    text: 'Ready to Publish?'
    ctas:
      - color: accent
        href: 'https://stoplight.io/p/docs'
        title: Get Started Now

meta:
  description: >-
    Create API documentation in minutes. Combine OpenAPI Specifications
    (formerly known as Swagger) with Markdown to create robust, searchable,
    internal and external API documentation for your organization. One-click
    cloud deployment with Stoplight or download the static assets to host
    anywhere.
  favicon: /images/mark_light_bg.png
  image: /images/docs_header.png
  title: REST API Documentation Generator | Hosted API Documentation
  twitter:
    description: >-
      Create API documentation in minutes. Combine OpenAPI Specifications
      (formerly known as Swagger) with Markdown to create robust, searchable,
      internal and external API documentation for your organization. One-click
      cloud deployment with Stoplight or download the static assets to host
      anywhere.
    image: /images/docs_header.png
    title: REST API Documentation Generator | Hosted API Documentation
    username: '@stoplightio'
